nodeLinker: pnp
nmMode: hardlinks-local
enableGlobalCache: false

packageExtensions:
  "@astrojs/solid-js@*":
    peerDependencies:
      solid-devtools: "*"
  "@effect/platform-node@*":
    peerDependencies:
      bufferutil: "^4.0.1"
      utf-8-validate: ">=5.0.2"
