nodeLinker: pnp
nmMode: hardlinks-local
enableGlobalCache: false

logFilters:
  - code: YN0069
    level: discard

packageExtensions:
  "@astrojs/solid-js@*":
    peerDependencies:
      solid-devtools: "*"
